# This is a basic workflow to help you get started with Actions

name: Data Update

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the "staging" branch
    push:
        branches: ["dev"]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    trigger:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            - name: POST call datagovmy dev
              uses: fjogeleit/http-request-action@v1
              with:
                  url: "https://seahorse-app-b46yq.ondigitalocean.app/update/"
                  method: "POST"
                  customHeaders: '{"Authorization": "${{ secrets.WORKFLOW_TOKEN_STAGING }}"}'
                  timeout: 30000
#            - name: POST call openapi staging
#              uses: fjogeleit/http-request-action@v1
#              with:
#                  url: "https://seahorse-app-b46yq.ondigitalocean.app/data-catalogue/update/"
#                  method: "POST"
#                  customHeaders: '{"Authorization": "${{ secrets.DATA_CATALOGUE_TOKEN_STAGING }}"}'
#                  timeout: 30000
